# Generated by Django 5.2.8 on 2025-11-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
    ]
