# Generated by Django 5.2.8 on 2025-11-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'managed': False},
        ),
    ]
