# Generated by Django 5.2.8 on 2025-12-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_id_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='email',
        ),
    ]
