# Generated by Django 5.2.8 on 2025-12-02 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.usuario'),
        ),
    ]
